if [ "${1}" = "" ]; then
  echo "formatting hole project"
#  golangci-lint run ./applications/"${1}"/...
  go fmt ./...
  go vet ./...
else
#  golangci-lint run ./applications/"${1}"/...
  go fmt ./applications/"${1}"/...
  go vet ./applications/"${1}"/...
fi